### PR TITLE
REFACTOR!

### PR DESCRIPTION
**Pull request by BlackGoku36**
Refactor the whole code base by splitting them into multiple files, because ~2000 lines of code are hard to read if they are in single file

Tree:

- Sources
   - Main.hx
   - arm2d
       - ~~Elements.hx~~ Editor.hx
       - ElementController.hx
       - Assets.hx
       - Path.hx
       - tools
           - CanvasTools.hx
           - Math.hx
       - ui
           - UIToolBar.hx
           - UIProperties.hx

Can anyone test it, it work fine for me

~~Do not merge yet~~

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
Maybe we should rename Elements.hx? What about Editor.hx?

**Comment by BlackGoku36** [comment]
Sound good!

**Comment by BlackGoku36** [comment]
There we go

**Comment by luboslenco** [comment]
Sweet!

**Pull request merged**
